name: Energy Data Pipeline CI-CD 

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC"
  
jobs:
  tests:
    name: Run Test
    uses: ./.github/workflows/test-lint.yaml
    secrets: inherit
    if: github.ref == 'refs/heads/main'