name: Lint Python Scripts and Run Tests

on:
  workflow_call

jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint Python scripts with Ruff
        run: |
          python -m ruff check src/ tests/

      - name: Run test with pytest
        run: |
          if ls tests/*.py 1> /dev/null 2>&1; then
            pytest -v tests/
          else
            echo "No tests found, skipping..."
          fi